"""Test file discovery and storage for the metadata reviewer."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from pydantic import ValidationError

from data_snapshot.metadata_reviewer.storage import (
    ReviewItem,
    discover_review_items,
    load_review_records,
    metadata_values_equal,
    save_gold,
)


def _write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value), encoding="utf-8")


def test_discovery_matches_exported_names_and_warns_for_excluded_files(
    tmp_path: Path,
) -> None:
    """Match unique stems while preserving warnings and source/type output paths."""

    snapshots = tmp_path / "snapshots"
    generated = tmp_path / "exported"
    gold = tmp_path / "gold"
    first_snapshot = snapshots / "unhcr" / "figure" / "alpha.png"
    second_snapshot = snapshots / "prwp" / "table" / "beta.png"
    invalid_snapshot = snapshots / "other" / "figure" / "excluded.png"
    for path in (first_snapshot, second_snapshot, invalid_snapshot):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b"png")
    _write_json(generated / "batch1" / "unhcr" / "alpha_metadata.json", {})
    _write_json(generated / "batch1" / "prwp" / "beta_metadata.json", {})
    _write_json(generated / "batch1" / "unhcr" / "orphan_metadata.json", {})
    existing_gold = gold / "elsewhere" / "beta.json"
    _write_json(existing_gold, {"title": "Reviewed"})

    result = discover_review_items(snapshots, generated, gold)

    assert [item.snapshot_id for item in result.items] == ["alpha", "beta"]
    assert result.items[0].gold_path == gold / "unhcr" / "figure" / "alpha.json"
    assert result.items[1].gold_path == existing_gold
    assert result.items[1].reviewed
    assert any("supported source" in warning for warning in result.warnings)
    assert any("orphan_metadata.json" in warning for warning in result.warnings)


def test_duplicate_normalized_stems_are_fatal(tmp_path: Path) -> None:
    """Reject duplicate IDs, including exporter-suffixed and plain JSON names."""

    snapshots = tmp_path / "snapshots"
    generated = tmp_path / "exported"
    snapshot = snapshots / "unhcr" / "figure" / "same.png"
    snapshot.parent.mkdir(parents=True)
    snapshot.write_bytes(b"png")
    _write_json(generated / "a" / "same.json", {})
    _write_json(generated / "b" / "same_metadata.json", {})

    with pytest.raises(ValueError, match="Duplicate generated ID 'same'"):
        discover_review_items(snapshots, generated, tmp_path / "gold")


def test_existing_gold_is_the_working_record(tmp_path: Path) -> None:
    """Load generated as reference and existing gold as an independent draft."""

    generated_path = tmp_path / "generated.json"
    gold_path = tmp_path / "gold.json"
    _write_json(generated_path, {"title": "Generated"})
    _write_json(gold_path, {"title": "Gold"})
    item = ReviewItem("sample", tmp_path / "sample.png", generated_path, gold_path)

    generated, working = load_review_records(item)
    working["title"] = "Changed again"

    assert generated == {"title": "Generated"}
    assert json.loads(gold_path.read_text(encoding="utf-8")) == {"title": "Gold"}


def test_comparison_treats_object_nulls_as_missing() -> None:
    """Ignore null object fields without collapsing invalid empty objects."""

    assert metadata_values_equal({"title": None}, {})
    assert metadata_values_equal(
        {"variables": [{"name": "Population", "unit": None}]},
        {"variables": [{"name": "Population"}]},
    )
    assert not metadata_values_equal({"project": {"name": None}}, {})
    assert not metadata_values_equal(["A", "B"], ["B", "A"])


def test_save_is_canonical_atomic_and_never_changes_generated(tmp_path: Path) -> None:
    """Write canonical gold JSON while leaving generated bytes unchanged."""

    generated_path = tmp_path / "exported" / "sample_metadata.json"
    gold_path = tmp_path / "gold" / "unhcr" / "figure" / "sample.json"
    _write_json(generated_path, {"title": "Generated"})
    original_generated = generated_path.read_bytes()
    item = ReviewItem("sample", tmp_path / "sample.png", generated_path, gold_path)

    metadata = save_gold(
        item,
        {
            "title": "  Gold title  ",
            "panel_titles": ["A", "A", "B"],
            "provenance": None,
        },
    )

    assert metadata.title == "Gold title"
    assert json.loads(gold_path.read_text(encoding="utf-8")) == {
        "title": "Gold title",
        "panel_titles": ["A", "B"],
    }
    assert gold_path.read_text(encoding="utf-8").endswith("\n")
    assert generated_path.read_bytes() == original_generated
    assert item.reviewed
    assert not list(gold_path.parent.glob("*.tmp"))


def test_invalid_save_preserves_existing_gold(tmp_path: Path) -> None:
    """Validate before writing so an invalid edit cannot damage existing gold."""

    generated_path = tmp_path / "generated.json"
    gold_path = tmp_path / "gold.json"
    _write_json(generated_path, {})
    _write_json(gold_path, {"title": "Existing gold"})
    original_gold = gold_path.read_bytes()
    item = ReviewItem("sample", tmp_path / "sample.png", generated_path, gold_path)

    with pytest.raises(ValidationError):
        save_gold(item, {"variables": [{}]})

    assert gold_path.read_bytes() == original_gold


def test_generated_and_gold_paths_cannot_overlap(tmp_path: Path) -> None:
    """Reject root and file configurations that could overwrite generated data."""

    snapshots = tmp_path / "snapshots"
    generated = tmp_path / "exported"
    snapshots.mkdir()
    generated.mkdir()

    with pytest.raises(ValueError, match="must not overlap"):
        discover_review_items(snapshots, generated, generated / "gold")

    generated_path = generated / "same.json"
    _write_json(generated_path, {})
    item = ReviewItem("same", tmp_path / "same.png", generated_path, generated_path)
    with pytest.raises(ValueError, match="cannot overwrite"):
        save_gold(item, {})
